### ISSUE TITLE
content router

### ISSUE THREAD

**Issue by mtiger2k** [libp2p/js-libp2p-pubsub-peer-discovery#11]
Hi experts,

The peer discovery works fine, but when I add data to one ipfs node, it's failed to get it from another ipfs node, until I swarm connect the two nodes.

So this is only peer discovery, not content router. How to achieve these two functionalities together?

thanks.

**Comment by achingbrain** [comment]
As you found this is a peer discovery module, not a content router.  You need some mechanism of looking up which peer hosts the block that corresponds to a given CID.  The current ways of doing this are a DHT lookup, [reframe](https://github.com/ipfs/specs/blob/main/reframe/REFRAME_PROTOCOL.md), or using a delegate node to do one or both on your behalf.

See: https://github.com/libp2p/js-libp2p-interfaces/tree/master/packages/interface-content-routing
