### ISSUE TITLE
onMessage doesn't work when listenOnly === true

### ISSUE THREAD

**Issue by sethhrbek** [libp2p/js-libp2p-pubsub-peer-discovery#29]
**Expected Behavior**
When `listenOnly: true` in config, broadcast doesn't get called, but the `onMessage` event listener should work.

**Actual Behavior**
`onMessage` doesn't work

This is b/c `isStarted` will return false unless the `intervalId` gets set, and the `intervalId` gets set only if `listenOnly: false`.

There should be a different mechanism by which `isStarted` is set (rather than it being derived from the intervalId)

**Comment by mpetrunic** [comment]
Should be fixed by https://github.com/libp2p/js-libp2p-pubsub-peer-discovery/pull/49
