### ISSUE TITLE
It's confusing to call this an "mdns like" peer discovery mechanism

### ISSUE THREAD

**Issue by TimDaub** [libp2p/js-libp2p-pubsub-peer-discovery#83]
- I know it's kind of silly from my side, but I've always discounted this library as using mdns for peer discovery given its tag line "A js-libp2p module that uses pubsub for mdns like peer discovery"
- "mdns" never fit my needs because I needed discovery on the internet too and so I was wondering why gossipsub nodes don't interconnect: https://github.com/ChainSafe/js-libp2p-gossipsub/issues/409
- It turns out, this library is necessary and uses gossipsub's pubsub mechanism to do the peer discovery

**Comment by maschad** [comment]
This library isn't necessarily required to peer discovery with GossipSub. [We explain the different Peer discovery mechanisms here](https://github.com/libp2p/js-libp2p/blob/db7d05d7cf1bdad77b28fc151b613faf3d296288/examples/discovery-mechanisms/README.md?plain=1#L1-L7) and you opt for a different peer discovery mechanism depending on your scenario

**Comment by TimDaub** [comment]
understood, thx
